version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - back-end
    depends_on:
      - events-hub-backend
  events-hub-backend:
    build:
      context: ./
      dockerfile: events-hub-backend/Dockerfile
    volumes:
      - ./events-hub-backend/instance/:/app/instance/
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ENABLE_UNSAFE_ADMIN=${ENABLE_UNSAFE_ADMIN:-false}
      - SIGHTENGINE_USER=${SIGHTENGINE_USER}
      - SIGHTENGINE_SECRET=${SIGHTENGINE_SECRET}
      - SIGHTENGINE_PHOTO_WORKFLOW=${SIGHTENGINE_PHOTO_WORKFLOW}
    networks:
      - back-end

networks:
  back-end:

volumes:
  nginx-conf:
  backend-data: